--
-- Script was generated by Devart dbForge Data Generator for SQL Server, Version 4.3.68.0
-- Product Home Page: http://www.devart.com/dbforge/sql/data-generator
-- Script date 01/11/2021 11:10:13 CH
-- Target server version: 15.00.2000
-- Target connection string: Connection Timeout=30;Data Source=DESKTOP-TTF1SC1\SQLEXPRESS;MultipleActiveResultSets=False;Integrated Security=True;Packet Size=4096;TrustServerCertificate=False;User ID=DESKTOP-TTF1SC1\lngkh
--



SET LANGUAGE 'English'
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

--
-- Backing up database QuanLyHoaDon
--
--
-- Create backup folder
--
IF OBJECT_ID('xp_create_subdir') IS NOT NULL
  EXEC xp_create_subdir N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\Backup'
--
-- Backup database to the file with the name: <database_name>_<yyyy>_<mm>_<dd>_<hh>_<mi>.bak
--
DECLARE @db_name SYSNAME
SET @db_name = N'QuanLyHoaDon'

DECLARE @filepath NVARCHAR(4000)
SET @filepath =
/*define base part*/ N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\Backup\' + @db_name + '_' +
/*append date*/ REPLACE(CONVERT(NVARCHAR(10), GETDATE(), 102), '.', '_') + '_' +
/*append time*/ REPLACE(CONVERT(NVARCHAR(5), GETDATE(), 108), ':', '_') + '.bak'

DECLARE @SQL NVARCHAR(MAX)
SET @SQL = 
    N'BACKUP DATABASE ' + QUOTENAME(@db_name) + ' TO DISK = @filepath WITH INIT' + 
      CASE WHEN EXISTS(
                SELECT value
                FROM sys.configurations WITH (NOLOCK)
                WHERE name = 'backup compression default'
          )
        THEN ', COMPRESSION'
        ELSE ''
      END

EXEC sys.sp_executesql @SQL, N'@filepath NVARCHAR(4000)', @filepath = @filepath
GO

USE QuanLyHoaDon
GO

IF DB_NAME() <> N'QuanLyHoaDon' SET NOEXEC ON
GO
--
-- Delete data from the table 'dbo.CT_HOADON'
--
TRUNCATE TABLE dbo.CT_HOADON
GO
--
-- Delete data from the table 'dbo.HOADON'
--
DELETE dbo.HOADON
GO

--
-- Set NOEXEC to off
--

SET NOEXEC OFF
GO